config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: 'home#show'

  resources :competencies, only: [:index, :show, :create, :update, :destroy]
  resources :learnables, :tags, :topics, :learning_sources

end

app/controllers/learnables_controller.rb
class LearnablesController < ApplicationController
  before_action :set_learnable, only: [:show, :edit, :update, :destroy]

  # GET /learnables
  # GET /learnables.json
  def index
    @learnables = Learnable.all
  end

  # GET /learnables/1
  # GET /learnables/1.json
  def show
  end

  # GET /learnables/new
  def new
    @learnable = Learnable.new
  end

  # GET /learnables/1/edit
  def edit
    @learnable = Learnable.find(params[:id])
  end

  # POST /learnables
  # POST /learnables.json
  def create
    @learnable = Learnable.new(learnable_params)

    respond_to do |format|
      if @learnable.save
        format.html { redirect_to @learnable, notice: 'Learnable was successfully created.' }
        format.json { render :show, status: :created, location: @learnable }
      else
        format.html { render :new }
        format.json { render json: @learnable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learnables/1
  # PATCH/PUT /learnables/1.json
  def update
    @learnable.update(learnable_params)
    add_tags
    add_topics
    respond_to do |format|
      if @learnable.save
        format.html { redirect_to @learnable, notice: 'Learnable was successfully updated.' }
        format.json { render :show, status: :ok, location: @learnable }
      else
        format.html { render :edit }
        format.json { render json: @learnable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learnables/1
  # DELETE /learnables/1.json
  def destroy
    @learnable.destroy
    respond_to do |format|
      format.html { redirect_to learnables_url, notice: 'Learnable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learnable
      @learnable = Learnable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learnable_params
      params.fetch(:learnables, {}).permit(:name)
    end

    def add_tags
      tags = params.fetch(:learnables, {}).permit(tag: :id)
      return unless tags.present?
      tag = Tag.find(tags[:tag][:id])
      @learnable.tags << tag unless @learnable.tags.include?(tag)
    end

    def add_topics
      topic = params.fetch(:topic, {}).permit(topic: :id)
      return unless topic.present?
      @learnable.competency = Learnable.find(topic[:topic][:id])
    end
end

app/helpers/learnable_helper.rb
module LearnableHelper
end

app/helpers/learnables_helper.rb
module LearnablesHelper
end

app/views/learnables/_form.html.erb
<%= form_for(@learnable) do |f| %>
  <% if @learnable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@learnable.errors.count, "error") %> prohibited this learnable from being saved:</h2>

      <ul>
      <% @learnable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/learnables/edit.html.erb
<h1>Editing Learnable</h1>

<%= render 'form' %>

<%= link_to 'Show', @learnable %> |
<%= link_to 'Back', learnables_path %>

app/views/learnables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Learnables</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @learnables.each do |learnable| %>
      <tr>
        <td><%= link_to 'Show', learnable %></td>
        <td><%= link_to 'Edit', edit_learnable_path(learnable) %></td>
        <td><%= link_to 'Destroy', learnable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Learnable', new_learnable_path %>

app/views/learnables/new.html.erb
<h1>New Learnable</h1>

<%= render 'form' %>

<%= link_to 'Back', learnables_path %>

app/views/learnables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_learnable_path(@learnable) %> |
<%= link_to 'Back', learnables_path %>